<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Admin-PC" ignored="0" name="SeleniumTrainingHandsOn" tests="6" failures="3" timestamp="19 Jun 2019 18:57:30 GMT" time="0.199" errors="0">
  <testcase name="testAddition" time="0.022" classname="com.github.prashantpalhade.calculator.TestSciCalculator"/>
  <testcase name="testDivision" time="0.001" classname="com.github.prashantpalhade.calculator.TestSciCalculator"/>
  <testcase name="testMulti" time="0.003" classname="com.github.prashantpalhade.calculator.TestSciCalculator">
    <failure type="java.lang.AssertionError" message="expected [50] but found [15]">
      <![CDATA[java.lang.AssertionError: expected [50] but found [15]
at com.github.prashantpalhade.calculator.TestSciCalculator.testMulti(TestSciCalculator.java:43)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testMulti -->
  <testcase name="testSqrRoot" time="0.001" classname="com.github.prashantpalhade.calculator.TestSciCalculator">
    <failure type="java.lang.AssertionError" message="expected [3] but found [3.0]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [3.0]
at com.github.prashantpalhade.calculator.TestSciCalculator.testSqrRoot(TestSciCalculator.java:11)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testSqrRoot -->
  <testcase name="testSubstract" time="0.001" classname="com.github.prashantpalhade.calculator.TestSciCalculator"/>
  <testcase name="testcube" time="0.0" classname="com.github.prashantpalhade.calculator.TestSciCalculator">
    <failure type="java.lang.AssertionError" message="expected [729] but found [729.0]">
      <![CDATA[java.lang.AssertionError: expected [729] but found [729.0]
at com.github.prashantpalhade.calculator.TestSciCalculator.testcube(TestSciCalculator.java:17)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testcube -->
</testsuite> <!-- SeleniumTrainingHandsOn -->
